### PR TITLE
Also start if there are AT LEAST N brokers available

### PR DESCRIPTION
**Pull request by blootsvoets**

### CODE REVIEW

**Comment by blootsvoets** [comment]
This fix can also be applied to other kafka components

**Comment by yatharthranjan** [comment]
Just curious, are you guys running RADAR-base with more than 3 brokers? if yes, is it for scalability or availability? And have you guys increased the number of partitions too (to reflect the increase in number of brokers) ?

**Comment by blootsvoets** [comment]
In the Kubernetes setup we use it for increased availability. We don’t increase the number of partitions, but this way the number of brokers exceeds the replication factor, so if a broker temporarily fails the replication factor does not need to decrease. We could increase the number of partitions as well, at an increased overhead, but it’s not necessary for us at this moment.

**Comment by yatharthranjan** [comment]
Ok. Thank you.

**Pull request merged**
