### PR TITLE
Fe paging

### PR DESCRIPTION
**Pull request by khoathanglong**
1. Pagination Records #29
2. Add filters and move filter controls to corresponding table

### CODE REVIEW

**Comment by khoathanglong** [comment]
> Alright, good first iteration, LGTM. Fine to merge if the test succeeds.
> 
> For a next iteration, I think it would make sense to visually distinguish the different layout items (tabs, filtering, table) by using a bit more coloring or sectioning. Not needed on this PR.

I would like to but I am not good at picking color and put them in the good way. I'm open to specific suggestions

**Comment by blootsvoets** [comment]
Does the Google Firebase layout help for layout ideas?

**Comment by khoathanglong** [comment]
ah ok, I 'll see if I can learn from them 🔢

**Comment by khoathanglong** [comment]
@blootsvoets  I could not figure out how one test did not run in travis but run ok in my local. Should you just merge or I remove that test first?

**Comment by khoathanglong** [comment]
I removed the failed test, but another test failed with exactly the same error ```  ● RecordTable › viewlogs
    connect ECONNREFUSED 127.0.0.1:80```

**Comment by blootsvoets** [comment]
In 9d34099, you added a `RecordTable.created()` implementation, that queries source types. Could it be that this needs to be mocked as well, so that no actual request is made?

**Comment by khoathanglong** [comment]
> In [9d34099](https://github.com/RADAR-base/radar-upload-source-connector/commit/9d340990d1ab72d4f93320eed4c07f332a8d0d7b), you added a `RecordTable.created()` implementation, that queries source types. Could it be that this needs to be mocked as well, so that no actual request is made?

I think you're right that the issue. Let me make the change and see if it works

**Pull request merged**
