### PR TITLE
Fix csv line processing

### PR DESCRIPTION
**Pull request by mpgxvii**
- Proceed processing even if line and header size do not match

### CODE REVIEW

**Review by blootsvoets — APPROVED** [review]
LGTM. Note that it may cause errors further down the line since records may be missing or incompatible

**Comment by mpgxvii** [comment]
@blootsvoets Yes I'll check first with the guys from Altoida since the warnings seem to be coming from the incorrectly formatted files.

**Comment by nivemaham** [comment]
Can we make this fix only for altoida? Plus, if the header and lines are not of the same size, the `zip` operation might fail. Did you have a change to test that?

**Comment by mpgxvii** [comment]
Closing since I'll be adding a different fix.

**Pull request closed without merging**
